---
title: "last_tree"
output: html_document
---

```{r}
library(ggtree)
library(stringr)
library(dplyr)
```

```{r}
# loading the tree
tree <- read.tree("/home/sedreh/Videos/my_last_results/bacteria_final_tree_labelled.nwk")
#creating group for groupinfo
n_tree <- tree
groupInfo <- split(n_tree$tip.label, gsub("(>\\w+)", "", n_tree$tip.label))

#Groupping OTUs for coloring the tree
final_tree <- groupOTU(n_tree, groupInfo)
#View(n_tree)
tr <- ggtree(final_tree,aes(color=group), layout="rectangular", branch.length="none") + geom_tiplab(size=0.2, align=TRUE, linesize=0.1)  + geom_tree() + theme_tree()+ theme(legend.position='none')+ geom_text(aes(label=node), hjust=-.1, size=2)
```


```{r}
statistics <- data.frame(read.csv("/home/sedreh/Videos/my_last_results/statistics.csv", sep = ","))

statistics$X <-NULL


```

```{r}
n_stat <- data.frame(statistics$node_id, statistics$X1, statistics$X2, statistics$X3, statistics$X4, statistics$X5, statistics$X6, statistics$X7, statistics$X8, statistics$X9,statistics$X10)

colnames(n_stat) <- c('node', 'c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10')

rownames(n_stat) <- n_stat$node_id
n_stat[is.na(n_stat)] <- 0
#node_list <- setNames(split(n_stat, seq(nrow(n_stat))), rownames(n_stat))
n_stat

```



```{r}

include_list <- data.frame(c("559","859","875","535","801","605","565","744","927","698","402","394","615","907","919","375","475","509","1007","1201","56","257","11","420","1143","1129","161","166","145","358","1059","319","327","121","133","1119","106","443","485","633","421","1060","1210","585","1070","762","821","67","341","147","78","755","12","868","851","726","568","17","511","493","1049","1023","397","487","770","909","607","1102","1121","1015","498","863","108","587","384","68","1179","802","793","930","777","806","959","757","344","1062","326")
                           )
  
 

colnames(include_list)<- 'V1'

node_subset <- subset(n_stat, node %in% include_list$V1)


pies <-   nodepie(node_subset, cols=2:11, alpha=1.0)

jpeg("/home/sedreh/Videos/my_last_results/pie_tree.jpeg", width = 5000, height = 30000, res = 1080)



#inset(tr, pies, width = 0.3, height = 0.3)


#pies
inset(tr, pies, width = 0.2, height =0.2)



dev.off()

#View(pies)
#View(p)
```
```{r}

```
